# OpenAPI specification draft for Backend API
openapi: 3.1.0
info:
  x-audience: external-public
  title: Backend API
  contact:
    name: bitshare
    email: email@example.com
  version: 1.0.0
components:
  schemas:
  parameters:
  responses:
servers:
  - url: https://example.com
    description: Development server
paths:
  /:
    get:
      description: >-
        Get interested data depending on parameters being passed.
        Core functionality.
  /health:
    get:
      description: >-
        Checking application's "health".
        Used for determining service's liveness (health check).
      responses:
        '200':
          description: Application can be considered as healthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    value: ok

